# Site specific settings
title: "Museifu Blog"
name: "Museifu Blog"
keywords: "Key, words, about, this, website"
baseurl: "/"
url: "http://museifu.com"
description: "S3cur1ty L0L"
cover: "/assets/img/cover.svg"
fanpage_id: ""

# Site general settings
lang: "en"
lang_alternate: "pt_BR"
ssl: false # It will redirect to https

# Media
# Just the shortname:
# facebook: lampiaosec # Rigth
# facebook: facebook.com/lampiaosec # Wrong
twitter: https://twitter.com/museifu_

# Build settings
markdown: kramdown
permalink: /:categories/:title/
