permalink: pretty
title:
███╗   ███╗██╗   ██╗███████╗███████╗██╗███████╗██╗   ██╗
████╗ ████║██║   ██║██╔════╝██╔════╝██║██╔════╝██║   ██║
██╔████╔██║██║   ██║███████╗█████╗  ██║█████╗  ██║   ██║
██║╚██╔╝██║██║   ██║╚════██║██╔══╝  ██║██╔══╝  ██║   ██║
██║ ╚═╝ ██║╚██████╔╝███████║███████╗██║██║     ╚██████╔╝
╚═╝     ╚═╝ ╚═════╝ ╚══════╝╚══════╝╚═╝╚═╝      ╚═════╝ 
                                                        
tagline: 'security things and security stuff'
url: https://museifu.com
paginate: 1
baseurl: "/"


# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
#ga_analytics:

# Specify the author for blog posts
author:
  name: museifu
  url: https://twitter.com/museifu_
  #email: museifu_
  
paginate: 5

# Custom vars
version: 3.0.0
